name: Feature request
description: Предложить новую возможность
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Какую проблему решаем?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Предложение решения
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Альтернативы
      placeholder: Какие другие варианты рассматривались?
